name: Run Selenium Tests with UI (Non-Headless)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Set up ChromeDriver
      uses: browser-actions/setup-chromedriver@latest

    - name: Start virtual display (Xvfb)
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 -ac &
        sleep 3

    - name: Run Maven tests
      run: |
        export DISPLAY=:99
        mvn test -Dsurefire.suiteXmlFiles=testng.xml
